export const BELT_RANK_ORDER = {
  white: 0,
  yellow: 1,
  orange: 2,
  purple: 3,
  blue: 4,
  green: 5,
  brown: 6,
  'brown-2': 7,
  red: 8,
  'red-2': 9,
  'red-3': 10,
  'black-temp': 11,
  'black-1': 12,
  'black-2': 13,
  'black-3': 14,
  'black-4': 15,
  'black-5': 16,
  'black-6': 17,
  'black-7': 18,
  'black-8': 19
}

export const BELT_COLORS_BG_TAILWIND = {
  white: 'bg-white',
  yellow: 'bg-yellow-300',
  orange: 'bg-orange-300',
  purple: 'bg-purple-300',
  blue: 'bg-blue-300',
  green: 'bg-green-300',
  brown: 'bg-amber-950',
  'brown-2': 'bg-amber-950',
  red: 'bg-red-300',
  'red-2': 'bg-red-300',
  'red-3': 'bg-red-300',
  'black-temp': 'bg-black',
  'black-1': 'bg-black',
  'black-2': 'bg-black',
  'black-3': 'bg-black',
  'black-4': 'bg-black',
  'black-5': 'bg-black',
  'black-6': 'bg-black',
  'black-7': 'bg-black',
  'black-8': 'bg-black',
}

export const BELT_COLORS_BORDER_TAILWIND = {
  white: 'border-gray-300',
  yellow: 'border-yellow-500',
  orange: 'border-orange-500',
  purple: 'border-purple-500',
  blue: 'border-blue-500',
  green: 'border-green-500',
  brown: 'border-amber-800',
  'brown-2': 'border-amber-800',
  red: 'border-red-800',
  'red-2': 'border-red-800',
  'red-3': 'border-red-800',
  'black-temp': 'border-gray-600',
  'black-1': 'border-black',
  'black-2': 'border-black',
  'black-3': 'border-black',
  'black-4': 'border-black',
  'black-5': 'border-black',
  'black-6': 'border-black',
  'black-7': 'border-black',
  'black-8': 'border-black',
}