export const BELT_COLORS_BG_TAILWIND = {
  white: 'bg-white',
  yellow: 'bg-yellow-300',
  orange: 'bg-orange-300',
  purple: 'bg-purple-300',
  blue: 'bg-blue-300',
  green: 'bg-green-300',
  brown: 'bg-amber-950',
  'brown-2': 'bg-amber-950',
  red: 'bg-red-300',
  'red-2': 'bg-red-300',
  'red-3': 'bg-red-300',
  'black-temp': 'bg-black',
  'black-1': 'bg-black',
  'black-2': 'bg-black',
  'black-3': 'bg-black',
  'black-4': 'bg-black',
  'black-5': 'bg-black',
  'black-6': 'bg-black',
  'black-7': 'bg-black',
  'black-8': 'bg-black',
}

export const BELT_COLORS_BORDER_TAILWIND = {
  white: 'border-white',
  yellow: 'border-yellow-300',
  orange: 'border-orange-300',
  purple: 'border-purple-300',
  blue: 'border-blue-300',
  green: 'border-green-300',
  // TODO: no brown?
  brown: 'border-brown-300',
  'brown-2': 'border-brown-500',
  red: 'border-red-300',
  'red-2': 'border-red-500',
  'red-3': 'border-red-700',
  'black-temp': 'border-gray-300',
  'black-1': 'border-zinc-300',
  'black-2': 'border-gray-500',
  'black-3': 'border-zinc-500',
  'black-4': 'border-gray-700',
  'black-5': 'border-zinc-700',
  'black-6': 'border-gray-900',
  'black-7': 'border-zinc-900',
  'black-8': 'border-black',
}