export const BELT_COLORS_BG_TAILWIND = {
  white: 'bg-white',
  yellow: 'bg-yellow-300',
  orange: 'bg-orange-300',
  purple: 'bg-purple-300',
  blue: 'bg-blue-300',
  green: 'bg-green-300',
  brown: 'bg-amber-950',
  'brown-2': 'bg-amber-950',
  red: 'bg-red-300',
  'red-2': 'bg-red-300',
  'red-3': 'bg-red-300',
  'black-temp': 'bg-black',
  'black-1': 'bg-black',
  'black-2': 'bg-black',
  'black-3': 'bg-black',
  'black-4': 'bg-black',
  'black-5': 'bg-black',
  'black-6': 'bg-black',
  'black-7': 'bg-black',
  'black-8': 'bg-black',
}

export const BELT_COLORS_BORDER_TAILWIND = {
  white: 'border-gray-300',
  yellow: 'border-yellow-500',
  orange: 'border-orange-500',
  purple: 'border-purple-500',
  blue: 'border-blue-500',
  green: 'border-green-500',
  brown: 'border-amber-800',
  'brown-2': 'border-amber-800',
  red: 'border-red-800',
  'red-2': 'border-red-800',
  'red-3': 'border-red-800',
  'black-temp': 'border-gray-600',
  'black-1': 'border-black',
  'black-2': 'border-black',
  'black-3': 'border-black',
  'black-4': 'border-black',
  'black-5': 'border-black',
  'black-6': 'border-black',
  'black-7': 'border-black',
  'black-8': 'border-black',
}